### ISSUE TITLE
Access violation in finalizer of PreparedSqlLiteInsertCommand

### ISSUE THREAD

**Issue by mj2015** [praeclarum/sqlite-net#1003]
I have some code that generates a complex object, then serialises it to JSON for storage in a sqlite database. Takes just over a minute to generate, then saves. I ran it and after about 80 inserts, it failed in the debugger saying that memory was corrupt. Odd, but I ran it again, and after about 110 more, same thing. 

      System.AccessViolationException
        HResult=0x80004003
       Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
       Source=<Cannot evaluate the exception source>
      StackTrace:
      <Cannot evaluate the exception stack trace>

     Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that 
    other memory is corrupt.
      at SQLitePCL.sqlite3_stmt.manual_close()
      at SQLite.PreparedSqlLiteInsertCommand.Finalize()

I have seen [issue 667](https://github.com/praeclarum/sqlite-net/issues/667) and it looks similar, but obviously not quite. On reviewing my code, I create an object for the generation, which creates a member property which is the database connection. This is created in the constructor, and used after the generation. There is no finaliser in the object that is dealing with the connection, so I guess it is garbage collected at some later time. The loop creates one of these objects, which does the work, inserts, and then it goes around again, so the original object is left to the garbage collector.

I shall add database closing to the object, but I am posting this for reference as it obviously will need fixing if it can be pinned down.

**Comment by mj2015** [comment]
Using version 1.7.355 - latest. Running under Windows 10 in Visual Studio for the fail.

**Comment by mj2015** [comment]
Okay, I added IDisposable to my class, Added .Dispose to the database connection, and it has run 150 loops with no issue. So that's a workaround, even if there is an underlying issue.

**Comment by JakobAnarkyLabs** [comment]
@mj2015 Thank you for your issue report. We were having the exact same issue, but ensuring that Dispose is called (in stead of the finalizer) does seem to be a functioning workaround :-)
