### ISSUE TITLE
NullReferenceException in SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery

### ISSUE THREAD

**Issue by madhuatlink** [praeclarum/sqlite-net#1022]
I am still getting the same issue explained here. https://github.com/praeclarum/sqlite-net/issues/761
Some times even if it throws the error at insert, later when I check actually the record has been inserted to the table.

I am using the sqlite-net version: 1.6.292

UWP target version - 18362
UWP Min version - 17763

 ```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery(Object[]) + 0x157
   at SQLite.SQLiteConnection.Insert(Object, String, Type) + 0x1ce
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass52_0.<InsertOrReplaceAsync>b__0(SQLiteConnectionWithLock) + 0x35
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass32_0`1.<WriteAsync>b__0() + 0x7a
   at System.Func`1.Invoke() + 0x28
   at System.Threading.Tasks.Task`1.InnerInvoke() + 0x25
   at System.Threading.Tasks.Task.Execute() + 0x1c
```

**Comment by chenxuuu** [comment]
meet same issue only on [linux arm test](https://github.com/chenxuuu/llcom/actions/runs/14429951334/job/40463534229):

```log
  Failed GetTest [32 ms]
  Error Message:
   Test method llcomTest.DatabaseTest.GetTest threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
  Stack Trace:
     at SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery(Object[] source)
   at SQLite.SQLiteConnection.Insert(Object obj, String extra, Type objType)
   at SQLite.SQLiteConnection.InsertOrReplace(Object obj)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass54_0.<InsertOrReplaceAsync>b__0(SQLiteConnectionWithLock conn)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass33_0`1.<WriteAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LLCOM.Services.Database._update(String key, String value) in /home/runner/work/llcom/llcom/llcomNext/LLCOM/Services/Database.cs:line 45
   at LLCOM.Services.Database.Set[T](String key, T value) in /home/runner/work/llcom/llcom/llcomNext/LLCOM/Services/Database.cs:line 60
   at llcomTest.DatabaseTest.GetTest() in /home/runner/work/llcom/llcom/llcomNext/llcomTest/DatabaseTest.cs:line 25
```
