### ISSUE TITLE
Exception: Library e_sqlite3 not found

### ISSUE THREAD

**Issue by markusalbrecht-procam** [praeclarum/sqlite-net#1099]
After instaling the NuGet into a .NetFramework 4.8 WPF Desktop App I always receive the following excveption when I try to establish the DB connection ?

   at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   at SQLite.SQLiteConnection..cctor()

The type initializer for 'SQLite.SQLiteConnection' threw an exception.

**Comment by markusalbrecht-procam** [comment]
The funny thing is that the DLL is located in the bin folder but for some reason not recognized - what could be the reason - is this not compatible with .NetFramework48 ?

**Comment by markusalbrecht-procam** [comment]
_System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'SQLite.SQLiteConnection' threw an exception.
  Source=SQLite-net
  StackTrace:
   at SQLite.SQLiteConnection..ctor(String databasePath, Boolean storeDateTimeAsTicks)
   at Procam.Gdm.DatabaseService.DatabaseConnection.GetDbConnection() in \Dev-ASYNC\DatabaseService\DatabaseConnection.cs:line 44

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
Exception: Library e_sqlite3 not found_

**Comment by markusalbrecht-procam** [comment]
I had a look at the sources and they are all in 
<TargetFramework>netstandard2.0</TargetFramework>
my complete solution is written with .NetFramework48, might that be the issue ?

**Comment by markusalbrecht-procam** [comment]
So the framework is definitely not an issue as 4.6 to 4.8 is supporting .NetStandard2.0, the DLL is there but not recognized, I will check the sources of this thing...

**Comment by markusalbrecht-procam** [comment]
OK I found the issue . the problem is that the Nuget ishould install the e_sqlite3.dll to the folders:

![image](https://user-images.githubusercontent.com/56921919/154444791-d1668532-4ae4-4ce1-9904-a95e44a52a89.png)

but when using a .NetFramwork4.8 project this is not done for whatever reason, seems to be a major issue between Core and .NetFramework. 

After generating this folders manually it works fine ;)

**Comment by ericsink** [comment]
It doesn't look like you've mentioned what version of sqlite-net or SQLitePCLRaw you are using.

I'm guessing you are building with AnyCPU.  I think the problem with the targets file may be something I fixed in this pre-release:

2.0.8-pre20220111224339

If you add PackageReference of SQLitePCLRaw.bundle_green at the above version, it should override the one brought in by sqlite-net and would probably fix the issue.

**Comment by markusalbrecht-procam** [comment]
Dear Erik.
Thanks for your assistance. Yes, I am using AnyCPU. I will try the mentioned fix as first tomorrow and give you feedback.
BR
Markus

**Comment by markusalbrecht-procam** [comment]
BTW I am using NuGet version 1.8.116 ;)

**Comment by markusalbrecht-procam** [comment]
Using the the prerelease solved the issue:
![image](https://user-images.githubusercontent.com/56921919/155289240-ff03b6b7-8d6f-4653-8818-19faf19e880d.png)
Greets!
Markus

**Comment by bbhxwl** [comment]
> Using the the prerelease solved the issue: ![image](https://user-images.githubusercontent.com/56921919/155289240-ff03b6b7-8d6f-4653-8818-19faf19e880d.png) Greets! Markus

I don't understand how to repair it. Can I copy it?

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/165053039-13e6ed7f-c21c-4e0a-a838-7a6c6cfcbb3d.png)

**Comment by MarcoMartins86** [comment]
Happened to me with `<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />`, the file is present in the exe path, but it's the Windows x86 version and is trying to load the x64 version. I'm using `Any CPU`.
```
Library e_sqlite3 not found
plat: win
suffix: DLL
possibilities (2):
    1) ...\bin\Debug\net462\runtimes\win-x64\native\e_sqlite3.dll
    2) ...\bin\Debug\net462\e_sqlite3.dll
win TryLoad: ...\bin\Debug\net462\runtimes\win-x64\native\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
win TryLoad: ...\bin\Debug\net462\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
NOT FOUND
```

**Comment by ericsink** [comment]
SQLitePCLRaw 3.x does this differently, and mostly better, but Any CPU is explicitly not supported, and the transition of sqlite-net to SQLitePCLRaw 3.x is still pending, see #1282 for more info.

**Comment by MarcoMartins86** [comment]
@ericsink thanks for the feedback.
If anyone is interested, I was able to get it to work with a workaround found in another thread (https://github.com/praeclarum/sqlite-net/issues/1115) for the .Net Framework 4.6.2.
Essentially, I embedded the `e_sqlite3.dll` using Costura, following the steps outlined in [this post](https://stackoverflow.com/a/63887710), and utilized `sqlite-net-base` instead of `sqlite-net-pcl` to manually set the provider to the file in the resources.
