### ISSUE TITLE
Add Web Assembly support

### ISSUE THREAD

**Issue by nesbox** [praeclarum/sqlite-net#1114]
When I try to create a DB in WASM app I get an error `dotnet.js:1  ---> System.DllNotFoundException: e_sqlcipher`

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception.
dotnet.js:1  ---> System.DllNotFoundException: e_sqlcipher
dotnet.js:1    at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\Runtime\InteropServices\NativeLibrary.Mono.cs:line 13
dotnet.js:1    at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\InteropServices\NativeLibrary.cs:line 94
dotnet.js:1    at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
dotnet.js:1    at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
dotnet.js:1    at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
dotnet.js:1    at SQLitePCL.Batteries_V2.Init()
dotnet.js:1    at SQLite.SQLiteConnection..cctor()
dotnet.js:1    --- End of inner exception stack trace ---
```

**Comment by ericsink** [comment]
Have you tried this with the latest pre-release of SQLitePCLRaw?
