### ISSUE TITLE
PRAGMA max_page_count "Not an error"

### ISSUE THREAD

**Issue by trampster** [praeclarum/sqlite-net#1117]
If I try and set the max_page_count pragma using the following code:

`_connection.Execute("PRAGMA max_page_count = 1024");`

I get this exception:

> Unhandled exception. SQLite.SQLiteException: not an error
>    at SQLite.SQLiteCommand.ExecuteNonQuery()
>    at SQLite.SQLiteConnection.Execute(String query, Object[] args)
>    at SingleSqlite.Database.<Start>b__8_0() in /home/daniel/Work/SingleSqlite/Database.cs:line 35
>    at AsyncThreading.AsyncThread.<>c__DisplayClass5_0.<<RunInThreadAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at SingleSqlite.Database.Start() in /home/daniel/Work/SingleSqlite/Database.cs:line 26
>    at Program.<Main>$(String[] args) in /home/daniel/Work/SingleSqlite/Program.cs:line 10
>    at Program.<Main>(String[] args)

Using DB Browser for SQLite on the same database I can get the PRAGMA no problem. (the new page count isn't to small for my existing database)

**Comment by jamesryanbell** [comment]
@trampster I'm getting the same error, did you get to the bottom of it please? Appreciate it's nearly 3 years ago you raised this!

**Comment by jamesryanbell** [comment]
Found it within the source code, looks like you have to run it via ExecuteScalar e.g.
`connection.ExecuteScalar<string>("PRAGMA journal_mode=MEMORY");`
