### ISSUE TITLE
net7.0-android support

### ISSUE THREAD

**Issue by jirisykora83** [praeclarum/sqlite-net#1159]
`System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception.
---> System.TypeLoadException: Could not load list of method overrides due to Method not found: int SQLitePCL.ISQLite3Provider.sqlite3_snapshot_get(SQLitePCL.sqlite3,SQLitePCL.utf8z,intptr&)
   at SQLitePCL.Batteries_V2.Init()
   at SQLite.SQLiteConnection..cctor()
   --- End of inner exception stack trace ---
   at Obletsvet.Ui.Mobile.MauiProgram.<>c.<CreateMauiApp>b__0_2(IServiceProvider x) in ..`

**Comment by jadenrogers** [comment]
Add these packages to your MAUI.csproj works fine

```
                <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.4" />
		<PackageReference Include="SQLitePCLRaw.core" Version="2.1.4" />
		<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.4" />
		<PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.4" />
```

**Comment by moonsmile-dev** [comment]
After installing `SQLitePCLRaw.bundle_green` as [official docs](https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/database-sqlite?view=net-maui-7.0), It worked well.
