### ISSUE TITLE
How to execute unit tests?

### ISSUE THREAD

**Issue by sapbucket** [praeclarum/sqlite-net#368]
I have a basic setup/installation question for SQLite.sln. I downloaded the source code from github and opened it with VS2012. It contained errors because nunit was not installed. After installing nunit and adding a reference, I was able to compile the project. However,  I cannot run the unit tests because sqlite3.dll is missing, and I get the error message at the end of this message. I tried to fix the issue by downloading sqlite3.dll from sqlite's homepage and adding a reference. This did not work (at all) - adding the reference resulted in a "could not load *.dll" message and the reference was not added. Please let me know what installation steps I am missing to get the unit tests running.

Thanks!

System.AggregateException : One or more errors occurred.

  ----> System.DllNotFoundException : Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SQLite.Tests.AsyncTests.FindAsyncWithExpression() in AsyncTests.cs: line 308
--DllNotFoundException
   at SQLite.SQLite3.Open(Byte[] filename, ref IntPtr db, Int32 flags, IntPtr zvfs)
   at SQLite.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks) in SQLite.cs: line 219
   at SQLite.SQLiteConnectionWithLock..ctor(SQLiteConnectionString connectionString, SQLiteOpenFlags openFlags) in SQLiteAsync.cs: line 488
   at SQLite.SQLiteConnectionPool.Entry..ctor(SQLiteConnectionString connectionString, SQLiteOpenFlags openFlags) in SQLiteAsync.cs: line 420
   at SQLite.SQLiteConnectionPool.GetConnection(SQLiteConnectionString connectionString, SQLiteOpenFlags openFlags) in SQLiteAsync.cs: line 453
   at SQLite.SQLiteAsyncConnection.GetConnection() in SQLiteAsync.cs: line 51
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass1.<CreateTablesAsync>b__0() in SQLiteAsync.cs: line 98
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by sapbucket** [comment]
I solved this by changing the project build settings from "Any CPU" to "x86". I also set the framework to version 4.0.
