### ISSUE TITLE
System.FormatException when parsing DateTime on some Systems

### ISSUE THREAD

**Issue by ps-mzamette** [praeclarum/sqlite-net#400]
On some systems a crash occurs when parsing the DateTime-String saved in the database. StoreDateTimeAsTicks is set to false.

```
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTime.Parse(String s)
   at SQLite.Net.SQLiteCommand.ReadCol(IDbStatement stmt, Int32 index, ColType type, Type clrType)
   at SQLite.Net.SQLiteCommand.<ExecuteDeferredQuery>d__2`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SQLite.Net.SQLiteCommand.ExecuteQuery[T]()
   at SQLite.Net.SQLiteConnection.Find[T](Object pk)
   at SQLiteNetExtensions.Extensions.ReadOperations.FindWithChildren[T](SQLiteConnection conn, Object pk, Boolean recursive)
   at SQLiteNetExtensionsAsync.Extensions.ReadOperations.<FindWithChildrenAsync>c__async2`1.<FindWithChildrenAsync>c__AnonStorey9.<>m__0()
```

I believe this bug is related to the following inconsistency: When saving the DateTime as string, the format (yyyy-MM-dd HH:mm:ss) gets specified, but not when parsing. Under certain conditions, parsing could fail due to localization issues. 

Maybe it would be better to use

``` csharp
return DateTime.ParseExact(text, "yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture);
```

instead of 

``` csharp
return DateTime.Parse (text);
```

in SQLite.Net.SQLiteCommand.ReadCol(IDbStatement stmt, Int32 index, ColType type, Type clrType). I believe that this change would prevent dependencies on localization settings and also improve the performance when parsing the string.

**Comment by nurchi** [comment]
Don't mean to troll, but the best thing to do is to convert all the `string` based `DateTime` fields to the ticks... This is universal (within .NET, but could be adapted for other platforms) and the value is fully preserved. In general, when you save the `DateTime` field on one machine and read it on another, the regional settings make a huge difference and they determine how the date/time fields are saved/read.

I believe, `SQLite` saves the `DateTime` as a string in a very specific format (you've got it in your question), but whether Windows expects the `DateTime` in that exact format is a big question. I would expect `sqlite-net` to take care of it, but you may have to browse through the parser and see for yourself.

So to answer your original question, `DateTime.ParseExact(...)` may be your next best option.

**Comment by praeclarum** [comment]
This has been fixed, but yes please switch to Ticks in the future. Thanks!
