### ISSUE TITLE
Failed to read '.Droid\obj\Release\linksrc\SQLite-net.dll' with debugging symbols.

### ISSUE THREAD

**Issue by candidodmv** [praeclarum/sqlite-net#576]
```
Mono.CompilerServices.SymbolWriter.MonoSymbolFileException: Symbol file `[PATH][SOLUTION NAME].Droid\obj\Release\linksrc\SQLite-net.dll.mdb' does not match assembly
   at Mono.CompilerServices.SymbolWriter.MonoSymbolFile.ReadSymbolFile(String mdbFilename, Guid assemblyGuid)
   at Mono.Cecil.Mdb.MdbReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   at Mono.Cecil.Cil.DefaultSymbolReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
```

**Comment by poliakov94** [comment]
Same problem here.
Downgrading to v1.3.0 with all SQLitePCLRaw. at v1.1.2 solved the problem.

**Comment by candidodmv** [comment]
I'm waiting for this bug fix came as soon

**Comment by praeclarum** [comment]
Have you tried upgrading to the v1.4 series? I switched to including portable PDBs and hope those will fix this for you.

**Comment by KSchaap** [comment]
I still get this issue, even when I downgraded to 1.3.1
