### ISSUE TITLE
Enums with elements that share values fail

### ISSUE THREAD

**Issue by mfkl** [praeclarum/sqlite-net#598]
Hi!

Thank you for your work on this ORM @praeclarum, it's greatly appreciated!

Just wanted to let you know that this code 
```
if (StoreAsText) 
{	
   EnumValues = Enum.GetValues (type).Cast<object> ().ToDictionary (Convert.ToInt32, x => x.ToString ());
}
else 
{
   EnumValues = Enum.GetValues (type).Cast<object> ().ToDictionary (Convert.ToInt32, x => Convert.ToInt32 (x).ToString ());
}
```
does not handle multiple enums having the same value, such as [VirtualKey](https://msdn.microsoft.com/fr-fr/library/windows/desktop/dd375731(v=vs.85).aspx?f=255&MSPPError=-2147217396) for example.
Stacktrace for reference:

```
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at SQLite.EnumCacheInfo..ctor(Type type)
   at SQLite.EnumCache.GetInfo(Type type)
   at SQLite.SQLiteCommand.BindParameter(sqlite3_stmt stmt, Int32 index, Object value, Boolean storeDateTimeAsTicks)
   at SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery(Object[] source)
   at SQLite.SQLiteConnection.Insert(Object obj, String extra, Type objType)
```

Is this a known limitation?

**Comment by praeclarum** [comment]
Ahh no, this is a bug. Will need to write a test for it. Thanks!
