### ISSUE TITLE
Cannot add "SQLite for Universal Windows Platform" extension to VS2017

### ISSUE THREAD

**Issue by jernelson7** [praeclarum/sqlite-net#682]
I'm creating a UWP project in VS2017. I included the SQLite.Net-PCL nuget but ran into this error: [https://stackoverflow.com/questions/4744293/unable-to-load-dll-sqlite3-the-specified-module-could-not-be-found-exceptio] . I tried the proposed fix of adding a reference to SQLite for Universal Windows Platform , but it was not yet installed. When I tried to install it, I got an error: "This extension is not compatible with Visual Studio 2017. Installation may cause Visual Studio to be unstable. Do you want to continue?". 
![image](https://user-images.githubusercontent.com/1328863/35048775-07dfcf20-fb6c-11e7-8018-48ace7a8177a.png)

I couldn't find any workaround, so I eventually allowed it to continue the install, and it seems to be working Ok. However, the warning is a bit disconcerting. I hope this doesn't cause problems down the line.

**Comment by jamesmontemagno** [comment]
This is not needed at all as that is an old extension. You only need this nuget and that is it.

**Comment by jernelson7** [comment]
That does not seem to be the case. If I remove the reference to SQLite for Universal Windows Platform, I get a runtime crash when trying to construct SQLitePlatformWinRT:

> System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=SQLite.Net.Platform.WinRT
  StackTrace:
   at SQLite.Net.Platform.WinRT.SQLite3.SetDirectory(UInt32 directoryType, String directoryPath)
   at SQLite.Net.Platform.WinRT.SQLiteApiWinRT..ctor()
   at SQLite.Net.Platform.WinRT.SQLitePlatformWinRT..ctor()

I'm referencing SQLite.Net-PCL v3.1.1 in the UWP project where the constructor is called.

**Comment by jamesmontemagno** [comment]
You are referencing the incorrect nuGet. That is a very old and outdated one.

You want: https://www.nuget.org/packages/sqlite-net-pcl

**Comment by jernelson7** [comment]
Thank you! I wasn't sure which nuget was being actively developed.
