### ISSUE TITLE
AccessViolationException when accessing from another thread

### ISSUE THREAD

**Issue by Mav986** [praeclarum/sqlite-net#901]
Hello. Not even sure if this is an issue, but since I couldn't find any documentation anywhere, I figured this was the best place to ask. I received the following exception which, I assume, was due to an attempt by 1 thread to read/write while another thread was read/writing. Is SQLite.NET not threadsafe? Do I need to synchronize access myself?

```csharp
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods.sqlite3_prepare_v2(IntPtr undefined, IntPtr undefined, Int32 undefined, IntPtr ByRef, IntPtr ByRef)
   at SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods.sqlite3_prepare_v2(IntPtr undefined, IntPtr undefined, Int32 undefined, IntPtr ByRef, IntPtr ByRef)
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_prepare_v2(IntPtr undefined, System.String undefined, IntPtr ByRef, System.String ByRef)
   at SQLitePCL.raw.sqlite3_prepare_v2(SQLitePCL.sqlite3 undefined, System.String undefined, SQLitePCL.sqlite3_stmt ByRef, System.String ByRef)
   at SQLitePCL.raw.sqlite3_prepare_v2(SQLitePCL.sqlite3 undefined, System.String undefined, SQLitePCL.sqlite3_stmt ByRef)
   at SQLite.SQLite3.Prepare2(SQLitePCL.sqlite3 undefined, System.String undefined)
   at SQLite.SQLiteCommand.Prepare()
   at SQLite.SQLiteCommand.ExecuteScalar[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]()
   at SQLite.TableQuery`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Count()
   at SQLite.TableQuery`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Count(System.Linq.Expressions.Expression`1> undefined)
   at SQLite.AsyncTableQuery`1+<>c__DisplayClass14_0[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].b__0(SQLite.SQLiteConnectionWithLock undefined)
   at SQLite.AsyncTableQuery`1+<>c__DisplayClass2_0`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].b__0()
   at System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object undefined)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread undefined, System.Threading.ExecutionContext undefined, System.Threading.ContextCallback undefined, System.Object undefined)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread undefined)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread undefined)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread undefined)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by ericsink** [comment]
What versions of sqlite-net and SQLitePCLRaw are you using?

And on which platform is this happening?

**Comment by Mav986** [comment]
sqlite-net-pcl v1.6.292

 I followed the directions in the repo README for nuget installation. Not sure how to check for SQLitePCLRaw, sorry.  I followed the directions in the repo README for nuget installation.

**Comment by ericsink** [comment]
In general, frequently opening and closing a SQLite connection is not considered a good idea, but the reasons are mostly to do with performance.  It shouldn't affect stability.

I'm not entirely sure this is a threading problem, but it still might be.

Unfortunately, my knowledge of sqlite-net itself is rather limited.  I maintain SQLitePCLRaw (the layer below).

The error message suggests a crash in the native code, rather than up in the managed layer.  This makes me wonder if the arguments passed down to `sqlite3_prepare_v2()` are in fact valid.  That's probably the first thing I would check.
