### ISSUE TITLE
Query silently fails (returns 0 results) only on UWP platform after database gets to certain size.

### ISSUE THREAD

**Issue by tomreich** [praeclarum/sqlite-net#981]
Hey folks.  Running into a very odd issue here.  It seems that once my database hits a certain size, certain queries begin silently failing by returning 0 results.  These queries work fine to a certain point, then suddenly stop.  The odd thing is that this is ONLY happening in UWP.  I created a Xamarin Forms app and cannot reproduce it in Android or iOS.  I also created a small .NET Core console app to try to reproduce it and, no dice.  However, the failure is repeatable on UWP.

Attached is a simple UWP application that will reproduce the problem that is based on a small subset of my app.  Start the application and click the button, then let it run for a while and watch the output window.  After a while you'll see the count from the query result go to 0 (see attached screenshot).

Any idea what's going on here?

[SQLiteUWPIssueRepro.zip](https://github.com/praeclarum/sqlite-net/files/5060524/SQLiteUWPIssueRepro.zip)
![sqlite-fail](https://user-images.githubusercontent.com/1900390/89973750-20cb7600-dc2f-11ea-8739-cbd19d885640.PNG)

**Comment by tomreich** [comment]
Anybody?  I've posted a repro...

**Comment by ericsink** [comment]
The repro app doesn't seem to work for me.  When I click Start, I don't get that stream of output you posted.

Nonetheless, my guess here is that the UWP build is having trouble because you haven't told SQLite where the sandbox directories are.

Try adding something like this in your app initialization:

```
            SQLitePCL.Batteries.Init();
            var rc = SQLitePCL.raw.sqlite3_win32_set_directory(
                1, // data
                Windows.Storage.ApplicationData.Current.LocalFolder.Path
                );
            // TODO check rc for errors

            rc = SQLitePCL.raw.sqlite3_win32_set_directory(
                2, // temp
                Windows.Storage.ApplicationData.Current.TemporaryFolder.Path
                );
            // TODO check rc for errors
```

**Comment by tomreich** [comment]
Thank you, it seems your hunch was correct.  The query is no longer failing after applying your snippet to OnLaunched() in App.xaml.cs.  I'm happy to close this out, but before I do, is there a reasonable way to change the failure behavior in this scenario?  Modify it in such a way that it throws an exception rather than just returning zero results?  Would have saved me a couple of hours, just trying to help others down the line save some time as well...

**Comment by ericsink** [comment]
"is there a reasonable way to change the failure behavior in this scenario?"

Maybe, but I'm not sure, and there would be risks.

I too think the behavior is strange, but it arises from deep within SQLite itself.

Another option would be to include these win32_set_directory calls in sqlite-net.  Microsoft.Data.Sqlite does this.

For completeness, note that SQLitePCLRaw 1.x did these calls, but they were removing in the 2.x cycle.

**Comment by apolloLegends** [comment]
All,

I have recently upgraded from 1.5 to 1.7 (and XF 4.3 to 4.8) and only UWP (so far) is giving me very weird behavior.  Some queries work but after adding new records(s) they fail.  Further, queries like this work:

- <sql>.Skip(1).FirstOrAsync() 
but the same sql
- <sql>.ToListAsync() returns 0 items... very confusing

Further, 
- Database.ExecuteAsync("Vacuum") throws:
   at SQLite.SQLiteCommand.ExecuteNonQuery()
   at SQLite.SQLiteConnection.Execute(String query, Object[] args)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass76_0.<ExecuteAsync>b__0(SQLiteConnectionWithLock conn)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass33_0`1.<WriteAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   <snip>

Ericsink's solution fixes all of this... perhaps the most telling piece of the equation was **Microsoft.Data.Sqlite does this** and **note that SQLitePCLRaw 1.x did these calls, but they were removing in the 2.x cycle**.

Much appreciated @ericsink

**Comment by captclearleft** [comment]
@ericsink - Wow!  Thank You!!!

That fixed my issue as well.  My sqlite queries all work fine in iOS, Android and even DB Browser for SQLite...  But in UWP as soon as the returned results were over like 600 rows (couldn't get exact number) - 

`var pairs = _databaseNA.Query<Pairings>(theQery);`

Would return 0 results.  If it was under 600 ish - It would work just fine.  So strange.  As soon as I added the code into the UWP Project App.xaml.cs OnLaunched() method - it works just fine.  (NOTE - Not the App.xaml.cs in the main code.  Its the one under the UWP specific Project. )
